<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);


session_start();

define('ROOT', dirname(__DIR__));

// calls the autoloader generated by composer
require_once ROOT . '/vendor/autoload.php';

require_once ROOT . '/app/config/connect.inc.php';
require_once ROOT . '/app/middleware/auth.php';
require_once ROOT . '/app/security/csrf.php';
require_once ROOT . '/app/config/config.php';
require_once ROOT . '/app/controller/UserController.php';

use Mawufemor\Techandfun\controller\UserController;
use Mawufemor\Techandfun\controller\CategoryController;
use Mawufemor\Techandfun\controller\PostController;


$pdo = Database::getInstance();


$userController = new UserController($pdo);
$categoryController = new CategoryController($pdo);
$postController = new PostController($pdo);


// function to check if user is logged in
function isLoggedIn()
{
    return isset($_SESSION['user_id']);
}

function isAdmin()
{
    return isset($_SESSION['role']) && $_SESSION['role'] === 'admin';
}

$page = $_GET['page'] ?? 'home';


switch ($page) {
    case 'home':
        require ROOT . '/app/view/public/home.php';
        break;
    case 'login':
        $userController->login();
        break;

    case 'register':
        $userController->register();
        break;

    case 'logout':
        $userController->logout();
        break;

    case 'categories':
        $categoryController->index();
        break;

    case 'create-categories':
        $categoryController->create();
        break;

    case 'store-category':
        $categoryController->store();
        break;

    case 'edit-category':
        $id = filter_var($_GET['id'] ?? null, FILTER_VALIDATE_INT);
        if ($id === false || $id === null) {
            $_SESSION['error'] = "Invalid category ID.";
            header("Location: ?page=categories");
            exit;
        }
        $categoryController->edit($id);
        break;


    case 'update-category':
        $id = filter_var($_GET['id'] ?? null, FILTER_VALIDATE_INT);
        if ($id === false || $id === null) {
            $_SESSION['error'] = "Invalid category ID.";
            header("Location: ?page=categories");
            exit;
        }
        $categoryController->update($id);
        break;


    case 'delete-category':
        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            http_response_code(405);
            exit('Invalid request method.');
        }

        $id = filter_var($_GET['id'] ?? null, FILTER_VALIDATE_INT);
        if ($id === false || $id === null) {
            $_SESSION['error'] = "Invalid category ID.";
            header("Location: ?page=categories");
            exit;
        }
        $categoryController->delete($id);
        break;

    case 'admin-dashboard':
        $userController->login();
        break;

    case 'blog':
        $postController->index();
        break;

    case 'create-post':
        $postController->create();
        break;

    case 'store-post':
        $postController->store();
        break;

    case 'blog-post':
        $slug = $_GET['slug'] ?? '';
        $postController->show($slug);
        break;

    case 'update-post-status':
        $postController->updateStatus();
        break;

        case 'edit-post':
        $id = filter_var($_GET['id'] ?? null, FILTER_VALIDATE_INT);
        if ($id === false || $id === null) {
            $_SESSION['error'] = "Invalid post ID.";
            header("Location: ?page=blog");
            exit;
        }
        $postController->edit($id);
        break;

        case 'update-post':
        $id = filter_var($_GET['id'] ?? null, FILTER_VALIDATE_INT);
        if ($id === false || $id === null) {
            $_SESSION['error'] = "Invalid post ID.";
            header("Location: ?page=blog");
            exit;
        }
        $postController->update($id);
        break;

    case 'error-404':
        require ROOT . '/app/view/error/404.php';
        break;

    default:
        http_response_code(404);
        echo "404 Page Not Found";
}
