<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);


session_start();

define('ROOT', dirname(__DIR__));

// calls the autoloader generated by composer
require_once ROOT . '/vendor/autoload.php';

require_once ROOT . '/app/config/connect.inc.php';
require_once ROOT . '/app/middleware/auth.php';
require_once ROOT . '/app/security/csrf.php';
require_once ROOT . '/app/config/config.php';
require_once ROOT . '/app/controller/UserController.php';

use Mawufemor\Techandfun\controller\UserController;
use Mawufemor\Techandfun\controller\CategoryController;


$pdo = Database::getInstance();


$userController = new UserController($pdo);
$categoryController = new CategoryController($pdo);

// function to check if user is logged in
function isLoggedIn()
{
    return isset($_SESSION['user_id']);
}

function isAdmin()
{
    return isset($_SESSION['role']) && $_SESSION['role'] === 'admin';
}

$page = $_GET['page'] ?? 'home';


switch ($page) {
    case 'home':
        require ROOT . '/app/view/public/home.php';
        break;
    case 'login':
        $userController->login();
        break;

    case 'register':
        $userController->register();
        break;

    case 'logout':
        $userController->logout();
        break;

    case 'categories':
        $categoryController->index();
        break;

    case 'create-categories':
        $categoryController->create();
        break;
        
    case 'store-category':
        $categoryController->store();
        break;

    default:
        http_response_code(404);
        echo "404 Page Not Found";
}
